/**:
  ros__parameters:
    use_sim_time: true
    qos_overrides:
      /clock:
        subscription:
          reliability: best_effort
          durability: volatile
          history: keep_last
          depth: 1