const english = {
  nav: { home: "Home", product: "Products", solutions: "Solutions", partners: "Partners", blog: "Blogs", contact: "Contact us", documentation: "Documentation" },
  dashboardAccess: { button: "Dashboard login", eyebrow: "AMR-X Control Center", title: "Coming soon", body: "A secure workspace for remote control, live robot status, missions, and fleet telemetry is currently being prepared.", features: ["Remote control", "Mission control", "Live telemetry"], note: "Dashboard access will open here when the first operator release is ready.", close: "Close" },
  hero: { eyebrow: "AMR-X / Autonomous modular robot — extended", title: "Modular autonomy, engineered as one platform.", body: "AMR-X is an engineering-stage autonomous mobile robot platform: a reusable indoor base, a common module boundary, ROS 2 autonomy, and operator software designed to evolve as one system.", primary: "Explore the platform", secondary: "See applications" },
  signals: [["01", "Reusable mobile foundation", "Keep mobility, navigation, compute, base power, safety coordination, and robot state coherent across every configuration."], ["02", "ROS 2 and digital twin", "Build repeatable descriptions, controllers, sensors, worlds, mapping, localization, and Nav2 integration before making hardware claims."], ["03", "Common module boundary", "Define how task modules mount, identify, communicate, receive power, report state, and remain inside reviewed safety constraints."], ["04", "Human-visible operation", "Make connection, mission state, command ownership, faults, recovery, and stale data understandable in both remote and local interfaces."]],
  showcase: {
    eyebrow: "The system in view",
    title: "Three directions for one modular platform.",
    body: "Move from remote operations to mobile manipulation and high-reach shelf access. Each view separates the intended application experience from the implementation maturity inside the repository.",
    tabLabel: "AMR-X system views",
    views: [
      { kind: "dashboard", label: "Teleoperations", short: "Remote control", status: "Preliminary data path / target interface", signal: "TELEOPERATION", frameLabel: "TARGET INTERFACE", title: "Remote operation needs one coherent picture.", body: "The repository already contains a preliminary browser teleoperation page, a ROS 2 dashboard bridge, and a FastAPI/PostgreSQL backend. This concept shows the intended next layer: location, mission progress, energy, safety, module state, camera context, and alerts in one workspace.", points: ["ROS data exposed through rosbridge and shared messages", "Browser teleoperation and state monitoring are preliminary", "Authentication, command authority, and the complete frontend remain open work"], image: "/images/showroom/web-dashboard-concept.png", alt: "AMR-X teleoperation dashboard showing a warehouse map, robot state, mission progress, safety, and telemetry" },
      { kind: "dual-arm", label: "Dual-arm robot", short: "Mobile manipulation", status: "Module concept / software scaffolding", signal: "MANIPULATION", frameLabel: "APPLICATION REFERENCE", title: "Bring dexterous work to the station.", body: "The dual-arm direction combines mobile navigation with task-level manipulation. The repository contains arm-description, control, interface, and MoveIt configuration scaffolds, but controller integration, planning configuration, stability validation, and the production mechanism are not complete.", points: ["Separate the reusable base from arm and end-effector responsibilities", "Coordinate payload, reach, stability, power, and safety constraints", "Validate navigation-to-manipulation hand-off in repeatable scenarios"], image: "/images/showroom/dual-arm-workcell.png", alt: "Dual-arm robotic workcell reference for the AMR-X mobile manipulation direction", fit: "contain" },
      { kind: "shelf", label: "Shelf access", short: "Vertical reach", status: "Application reference / early research", signal: "SHELF ACCESS", frameLabel: "APPLICATION REFERENCE", title: "Extend mobile autonomy into vertical storage.", body: "Shelf-access robotics represents a future module and mechanism study for high-bay inventory, inspection, and retrieval. The image communicates the application class; it is not released AMR-X geometry or evidence of an implemented lifting system.", points: ["Treat lift or climbing mechanics as a task module with explicit limits", "Preserve localization, load stability, obstacle handling, and recovery", "Define human-visible state and safe fallback for every vertical operation"], image: "/images/showroom/shelf-access-robot.png", alt: "Shelf-access robotic system reference in a warehouse", fit: "contain" }
    ]
  },
  web3d: { eyebrow: "Interactive engineering workflow", title: "CAD should become a product surface.", body: "The current viewer is an external mobile-manipulator reference, not AMR-X geometry. It demonstrates the expected delivery standard for future platform and module work: optimized, web-ready 3D exports that can be inspected without turning the model into a video.", credit: "External 3D reference — CC Attribution" },
  product: { eyebrow: "Platform architecture", title: "Change the capability, preserve the foundation.", body: "The project separates reusable base responsibilities from task-specific mechanisms. That boundary creates a disciplined route from indoor transport to manipulation, inspection, and controlled material handling.", cards: [["Mobile foundation", "Chassis, mobility, navigation, sensing, compute, base power and safety coordination.", "amr-x-base-cad-side-view.png", "foundation"], ["Manipulation module", "An engineering concept for bringing task tooling and arm capability to the point of work.", "dual-arm-module-concept-render.png", "manipulation"], ["Controlled transport", "A compartment-module concept for monitored movement and explicit hand-off workflows.", "secure-compartment-module-cad.png", "secure-transport"]], cta: "Discover AMR-X" },
  solutions: { eyebrow: "Application direction", title: "One architecture, validated against different indoor missions.", body: "AMR-X uses representative workflows to expose real interface, navigation, safety, and operator requirements. These are validation scenarios—not claims of production deployment.", items: [["Intralogistics", "Model station-to-station movement of parts, bins, and supplies without tying the base to one payload."], ["Mobile manipulation", "Study how arm capability, navigation, stability, and operator oversight come together on one mobile system."], ["Inspection", "Carry sensing payloads through repeatable routes while preserving localization, diagnostics, and traceable outcomes."], ["Controlled delivery", "Define observable hand-offs for sensitive tools, samples, or materials through explicit mission states."]] },
  vision: { eyebrow: "Engineering direction", title: "Make adaptation measurable and operation understandable.", body: "The project is organized around stable interfaces, repeatable validation, and one shared state model across the robot and its operator tools.", goals: [["Separate", "Keep base, module, navigation, mission, interface, and hardware responsibilities explicit."], ["Validate", "Use the digital twin, focused subsystem tests, and integrated scenarios before hardware claims."], ["Observe", "Expose mission state, faults, recovery, and command ownership clearly to people."]] },
  partners: { eyebrow: "Collaborative ecosystem", title: "Better robotics is built across disciplines.", body: "AMR-X welcomes conversations with technology suppliers, research teams, integrators and operational pilot sites.", items: [["Technology", "Sensors, compute, batteries, drives and safety components."], ["Research", "Autonomy, manipulation, perception and human–robot interaction."], ["Integration", "Deployment experience, workflows and application engineering."], ["Pilot sites", "Real use cases that turn assumptions into measurable requirements."]], cta: "Explore partnerships", ecosystem: "Technology ecosystem" },
  blog: { eyebrow: "Engineering journal", title: "Decisions behind a modular robot in development.", body: "Editorial previews connect product intent to the architecture choices, simulations, interfaces, and validation work inside the repository.", posts: [["Architecture", "Why modularity starts with the base", "Separating shared mobility and autonomy from task-specific mechanisms turns modularity into a system contract."], ["Autonomy", "From repeatable simulation to credible motion", "A practical look at robot description, sensors, mapping, localization, Nav2, and the evidence still needed beyond simulation."], ["Interaction", "Operator trust is part of the architecture", "Mission state, data freshness, faults, recovery, and command authority must be designed before an interface can feel dependable."]], read: "Preview story" },
  contact: { eyebrow: "Contact", title: "Let’s explore where AMR-X could create value.", body: "Tell us about a workflow, technology, research topic or pilot opportunity. This form is ready for connection to the project’s chosen contact service.", fields: { name: "Name", email: "Work email", organization: "Organization", subject: "I’m interested in", message: "Tell us about the opportunity", send: "Send inquiry" }, note: "Contact delivery will be enabled when the project selects its public inbox or CRM endpoint." },
  pageHeroes: {
    product: ["The platform", "A common foundation for changing robot capability.", "Explore the base responsibilities, module boundary, and engineering concepts that shape AMR-X."],
    solutions: ["Application direction", "Different missions. One controlled system boundary.", "See the indoor scenarios used to exercise navigation, modules, mission behavior, and operator oversight."],
    partners: ["Partner ecosystem", "Build the next layer of mobile robotics together.", "AMR-X is shaped by real components, real environments and collaborative validation."],
    blog: ["AMR-X journal", "Product thinking from a robot in development.", "Updates on modularity, autonomy, interaction design and the path from concept to deployment."],
    contact: ["Start a conversation", "Bring us the workflow that should move better.", "Share a use case, partnership idea or pilot opportunity."],
  },
  common: { learn: "Learn more", contact: "Contact us", viewSolutions: "View solutions" },
  footer: { summary: "An engineering-stage modular autonomous mobile robot platform for adaptable indoor missions.", explore: "Explore", connect: "Connect", legal: "Legal", social: "Follow us", product: "Products", solutions: "Solutions", partners: "Partners", blog: "Blogs", contact: "Contact", impressum: "Impressum", privacy: "Privacy", terms: "Terms of use", follow: "CYBERMECH SYSTEMS social links", instagramSoon: "Instagram — coming soon", copyright: "All rights reserved.", rights: "AMR-X engineering project. Concept visuals and planned capabilities are identified where shown." },
};

const localized = {
  fr: {
    nav: { home: "Accueil", product: "Produits", solutions: "Solutions", partners: "Partenaires", blog: "Blogs", contact: "Nous contacter", documentation: "Documentation" },
    dashboardAccess: { button: "Connexion dashboard", eyebrow: "Centre de contrôle AMR-X", title: "Bientôt disponible", body: "Un espace sécurisé pour le contrôle à distance, l’état du robot, les missions et la télémétrie est en préparation.", features: ["Contrôle à distance", "Gestion des missions", "Télémétrie en direct"], note: "L’accès sera activé ici dès la première version opérateur.", close: "Fermer" },
    hero: { eyebrow: "AMR-X / Robot autonome modulaire — étendu", title: "L’autonomie modulaire, conçue comme une seule plateforme.", body: "AMR-X est une plateforme de robot mobile autonome en phase d’ingénierie : une base intérieure réutilisable, une interface module commune, l’autonomie ROS 2 et des outils opérateur conçus comme un seul système.", primary: "Explorer la plateforme", secondary: "Voir les applications" },
    signals: [["01", "Fondation mobile réutilisable", "Maintenir la mobilité, la navigation, le calcul, l’alimentation de base, la coordination de sécurité et l’état du robot cohérents dans chaque configuration."], ["02", "ROS 2 et jumeau numérique", "Construire des descriptions, contrôleurs, capteurs, mondes, cartes, localisations et intégrations Nav2 reproductibles avant toute affirmation matérielle."], ["03", "Interface module commune", "Définir le montage, l’identification, la communication, l’alimentation, l’état et les contraintes de sécurité de chaque module métier."], ["04", "Exploitation lisible par l’humain", "Rendre la connexion, la mission, l’autorité de commande, les défauts, la reprise et la fraîcheur des données compréhensibles localement et à distance."]],
    showcase: { ...english.showcase, title: "Trois directions pour une plateforme modulaire.", body: "Passez des opérations à distance à la manipulation mobile puis à l’accès en hauteur. Chaque vue distingue l’expérience visée de la maturité réelle du dépôt.", tabLabel: "Vues système AMR-X", views: [
      { ...english.showcase.views[0], label: "Téléopérations", short: "Contrôle à distance", status: "Chaîne de données préliminaire / interface cible", title: "L’exploitation à distance exige une vue cohérente.", body: "Le dépôt contient déjà une page préliminaire de téléopération, un pont ROS 2 et un backend FastAPI/PostgreSQL. Ce concept montre l’étape suivante visée : localisation, mission, énergie, sécurité, module, caméra et alertes dans un même espace.", points: ["Données ROS exposées par rosbridge et des messages partagés", "Téléopération et surveillance encore préliminaires", "Authentification, autorité de commande et frontend complet restent à réaliser"] },
      { ...english.showcase.views[1], label: "Robot à deux bras", short: "Manipulation mobile", status: "Concept module / socle logiciel", title: "Amener la dextérité jusqu’au poste de travail.", body: "Cette direction associe navigation mobile et manipulation. Les descriptions de bras, interfaces, contrôles et configurations MoveIt sont amorcés, mais l’intégration, la planification, la stabilité et le mécanisme final restent incomplets.", points: ["Séparer les responsabilités de la base, des bras et des effecteurs", "Coordonner charge, portée, stabilité, énergie et sécurité", "Valider le passage navigation–manipulation dans des scénarios reproductibles"] },
      { ...english.showcase.views[2], label: "Accès aux rayonnages", short: "Portée verticale", status: "Référence applicative / étude initiale", title: "Étendre l’autonomie mobile au stockage vertical.", body: "L’accès aux rayonnages représente une future étude de module et de mécanisme pour l’inventaire, l’inspection et la récupération en hauteur. L’image illustre la classe d’application, pas une géométrie AMR-X validée.", points: ["Traiter le levage comme un module avec des limites explicites", "Préserver localisation, stabilité, évitement et reprise", "Définir un état lisible et un repli sûr pour chaque mouvement vertical"] }
    ] },
    product: { ...english.product, eyebrow: "Vision produit", title: "Une plateforme qui évolue avec la mission.", body: "La mobilité, l’énergie, la sécurité et l’autonomie restent dans la base. Le matériel métier change au-dessus.", cta: "Découvrir AMR-X" },
    solutions: { ...english.solutions, eyebrow: "Solutions", title: "Une automatisation adaptable aux besoins opérationnels.", body: "La vision cible les tâches intérieures répétables où mobilité et outils doivent évoluer indépendamment." },
    vision: { ...english.vision, eyebrow: "Orientation du projet", title: "Rendre la robotique avancée plus facile à adapter, valider et exploiter." },
    partners: { ...english.partners, eyebrow: "Écosystème collaboratif", title: "La robotique progresse grâce à plusieurs disciplines.", cta: "Explorer les partenariats", ecosystem: "Écosystème technologique" },
    blog: { ...english.blog, eyebrow: "Journal", title: "Idées, progrès et réflexion produit.", read: "Lire l’article" },
    contact: { ...english.contact, eyebrow: "Contact", title: "Explorons la valeur que pourrait créer AMR-X.", fields: { name: "Nom", email: "E-mail professionnel", organization: "Organisation", subject: "Sujet", message: "Décrivez l’opportunité", send: "Envoyer" } },
    common: { learn: "En savoir plus", contact: "Nous contacter", viewSolutions: "Voir les solutions" },
    footer: { ...english.footer, summary: "Une vision de robot mobile autonome et modulaire pour des opérations intérieures adaptables.", explore: "Explorer", connect: "Contact", legal: "Mentions légales", social: "Suivez-nous", product: "Produits", solutions: "Solutions", partners: "Partenaires", blog: "Blogs", contact: "Contact", impressum: "Mentions légales", privacy: "Confidentialité", terms: "Conditions d’utilisation", instagramSoon: "Instagram — bientôt disponible", copyright: "Tous droits réservés.", rights: "Vision produit AMR-X. Les concepts présentés continuent d’évoluer." },
  },
  de: {
    nav: { home: "Start", product: "Produkte", solutions: "Lösungen", partners: "Partner", blog: "Blogs", contact: "Kontakt", documentation: "Dokumentation" },
    dashboardAccess: { button: "Dashboard-Login", eyebrow: "AMR-X Kontrollzentrum", title: "Demnächst verfügbar", body: "Ein sicherer Arbeitsbereich für Fernsteuerung, Roboterstatus, Missionen und Flottentelemetrie wird derzeit vorbereitet.", features: ["Fernsteuerung", "Missionssteuerung", "Live-Telemetrie"], note: "Der Zugang wird hier mit der ersten Bedienerversion freigeschaltet.", close: "Schließen" },
    hero: { eyebrow: "AMR-X / Erweiterter modularer autonomer Roboter", title: "Modulare Autonomie als eine Plattform entwickelt.", body: "AMR-X ist eine autonome mobile Roboterplattform in der Entwicklungsphase: wiederverwendbare Indoor-Basis, gemeinsame Modulschnittstelle, ROS-2-Autonomie und Bedienwerkzeuge als zusammenhängendes System.", primary: "Plattform erkunden", secondary: "Anwendungen ansehen" },
    signals: [["01", "Wiederverwendbare mobile Basis", "Mobilität, Navigation, Rechner, Basisenergie, Sicherheitskoordination und Roboterzustand bleiben über jede Konfiguration hinweg konsistent."], ["02", "ROS 2 und digitaler Zwilling", "Reproduzierbare Beschreibungen, Regler, Sensoren, Welten, Karten, Lokalisierung und Nav2-Integration vor Hardwareaussagen aufbauen."], ["03", "Gemeinsame Modulschnittstelle", "Montage, Identifikation, Kommunikation, Energie, Zustand und geprüfte Sicherheitsgrenzen für Aufgabenmodule eindeutig festlegen."], ["04", "Nachvollziehbarer Betrieb", "Verbindung, Mission, Befehlsgewalt, Fehler, Wiederherstellung und Datenalter lokal wie aus der Ferne verständlich machen."]],
    showcase: { ...english.showcase, title: "Drei Richtungen für eine modulare Plattform.", body: "Wechseln Sie zwischen Fernbetrieb, mobiler Manipulation und Regalzugang. Jede Ansicht trennt das angestrebte Anwendungserlebnis vom tatsächlichen Reifegrad im Repository.", tabLabel: "AMR-X Systemansichten", views: [
      { ...english.showcase.views[0], label: "Teleoperation", short: "Fernsteuerung", status: "Vorläufiger Datenpfad / Zieloberfläche", title: "Fernbetrieb braucht ein konsistentes Gesamtbild.", body: "Das Repository enthält bereits eine vorläufige Browser-Teleoperation, eine ROS-2-Dashboard-Bridge und ein FastAPI/PostgreSQL-Backend. Das Konzept zeigt die nächste Zielstufe mit Position, Mission, Energie, Sicherheit, Modul, Kamera und Alarmen.", points: ["ROS-Daten über rosbridge und gemeinsame Nachrichten", "Teleoperation und Zustandsanzeige sind vorläufig", "Authentifizierung, Befehlsgewalt und vollständiges Frontend sind offen"] },
      { ...english.showcase.views[1], label: "Zweiarm-Roboter", short: "Mobile Manipulation", status: "Modulkonzept / Softwaregerüst", title: "Geschickte Manipulation direkt zur Arbeitsstation bringen.", body: "Die Zweiarm-Richtung verbindet mobile Navigation mit Aufgabenmanipulation. Beschreibungs-, Steuerungs-, Schnittstellen- und MoveIt-Gerüste existieren, doch Integration, Planung, Stabilität und Produktionsmechanik sind nicht abgeschlossen.", points: ["Verantwortung von Basis, Armen und Endeffektoren trennen", "Nutzlast, Reichweite, Stabilität, Energie und Sicherheit koordinieren", "Übergang von Navigation zu Manipulation reproduzierbar validieren"] },
      { ...english.showcase.views[2], label: "Regalzugang", short: "Vertikale Reichweite", status: "Anwendungsreferenz / frühe Studie", title: "Mobile Autonomie auf vertikale Lagerung ausdehnen.", body: "Regalzugangsrobotik ist eine künftige Modul- und Mechanismusstudie für Hochregallager, Inspektion und Entnahme. Das Bild vermittelt die Anwendungsklasse, nicht freigegebene AMR-X-Geometrie.", points: ["Hub- oder Klettermechanik als begrenztes Aufgabenmodul behandeln", "Lokalisierung, Laststabilität, Hindernisse und Wiederherstellung erhalten", "Für jede Vertikalbewegung sichtbaren Zustand und sicheren Rückfall definieren"] }
    ] },
    product: { ...english.product, eyebrow: "Produktvision", title: "Eine Plattform, die sich mit der Mission verändert.", body: "Mobilität, Energie, Sicherheit und Autonomie bleiben in der Basis. Die aufgabenspezifische Hardware wird oben gewechselt.", cta: "AMR-X entdecken" },
    solutions: { ...english.solutions, title: "Anpassbare Automatisierung für reale Betriebsanforderungen.", body: "Die Vision richtet sich an wiederholbare Indoor-Aufgaben, bei denen Mobilität und Werkzeuge unabhängig wachsen." },
    vision: { ...english.vision, eyebrow: "Projektrichtung", title: "Fortschrittliche Robotik leichter anpassbar, prüfbar und bedienbar machen." },
    partners: { ...english.partners, eyebrow: "Kooperatives Ökosystem", title: "Bessere Robotik entsteht über Fachgrenzen hinweg.", cta: "Partnerschaften erkunden", ecosystem: "Technologie-Ökosystem" },
    blog: { ...english.blog, title: "Ideen, Fortschritt und Produktdenken.", read: "Artikel lesen" },
    contact: { ...english.contact, title: "Lassen Sie uns den möglichen Nutzen von AMR-X erkunden.", fields: { name: "Name", email: "Geschäftliche E-Mail", organization: "Organisation", subject: "Interesse", message: "Beschreiben Sie die Gelegenheit", send: "Anfrage senden" } },
    common: { learn: "Mehr erfahren", contact: "Kontakt", viewSolutions: "Lösungen ansehen" },
    footer: { ...english.footer, summary: "Eine modulare autonome mobile Roboter-Vision für anpassbare Indoor-Prozesse.", explore: "Entdecken", connect: "Kontakt", legal: "Rechtliches", social: "Folgen Sie uns", product: "Produkte", solutions: "Lösungen", partners: "Partner", blog: "Blogs", contact: "Kontakt", impressum: "Impressum", privacy: "Datenschutz", terms: "Nutzungsbedingungen", instagramSoon: "Instagram — demnächst", copyright: "Alle Rechte vorbehalten.", rights: "AMR-X Produktvision. Gezeigte Konzepte werden weiterentwickelt." },
  },
  ar: {
    nav: { home: "الرئيسية", product: "المنتجات", solutions: "الحلول", partners: "الشركاء", blog: "المدونات", contact: "اتصل بنا", documentation: "التوثيق" },
    dashboardAccess: { button: "دخول لوحة التحكم", eyebrow: "مركز تحكم AMR-X", title: "قريبًا", body: "نعمل على إعداد مساحة آمنة للتحكم عن بُعد وحالة الروبوت والمهام وبيانات الأسطول المباشرة.", features: ["التحكم عن بُعد", "إدارة المهام", "البيانات المباشرة"], note: "سيتوفر الدخول من هنا عند إطلاق النسخة الأولى للمشغّلين.", close: "إغلاق" },
    hero: { eyebrow: "AMR-X / روبوت ذاتي معياري موسّع", title: "استقلالية معيارية صُممت كمنصة واحدة.", body: "AMR-X منصة روبوت متنقل ذاتي في مرحلة التطوير الهندسي: قاعدة داخلية قابلة لإعادة الاستخدام، وحدّ مشترك للوحدات، واستقلالية ROS 2، وأدوات تشغيل تتطور كنظام واحد.", primary: "استكشف المنصة", secondary: "شاهد التطبيقات" },
    signals: [["01", "قاعدة متنقلة قابلة لإعادة الاستخدام", "الحفاظ على اتساق الحركة والملاحة والحوسبة وطاقة القاعدة وتنسيق السلامة وحالة الروبوت في كل تهيئة."], ["02", "ROS 2 والتوأم الرقمي", "بناء أوصاف ووحدات تحكم وحساسات وبيئات وخرائط وتموضع وتكامل Nav2 قابلة للتكرار قبل إصدار ادعاءات عن العتاد."], ["03", "حدّ مشترك للوحدات", "تحديد التركيب والتعريف والاتصال والطاقة والحالة وقيود السلامة المراجعة لكل وحدة وظيفية."], ["04", "تشغيل واضح للإنسان", "جعل الاتصال والمهمة وسلطة الأوامر والأعطال والاستعادة وحداثة البيانات مفهومة في الواجهات المحلية والبعيدة." ]],
    showcase: { ...english.showcase, title: "ثلاثة اتجاهات لمنصة معيارية واحدة.", body: "انتقل بين التشغيل عن بُعد والمعالجة المتنقلة والوصول الرأسي إلى الرفوف. تفصل كل واجهة بين تجربة التطبيق المستهدفة ومستوى النضج الفعلي في المستودع.", tabLabel: "واجهات نظام AMR-X", views: [
      { ...english.showcase.views[0], label: "التشغيل عن بُعد", short: "التحكم عن بُعد", status: "مسار بيانات أولي / واجهة مستهدفة", title: "التشغيل عن بُعد يحتاج إلى صورة موحّدة.", body: "يحتوي المستودع على صفحة أولية للتحكم عن بُعد وجسر ROS 2 وخلفية FastAPI/PostgreSQL. يوضح هذا التصور المرحلة المستهدفة التالية: الموقع والمهمة والطاقة والسلامة والوحدة والكاميرا والتنبيهات في مساحة واحدة.", points: ["عرض بيانات ROS عبر rosbridge ورسائل مشتركة", "التحكم والمراقبة ما زالا أوليين", "المصادقة وسلطة الأوامر والواجهة الكاملة أعمال مفتوحة"] },
      { ...english.showcase.views[1], label: "روبوت بذراعين", short: "معالجة متنقلة", status: "تصور وحدة / هيكل برمجي أولي", title: "إيصال القدرة على المعالجة إلى محطة العمل.", body: "يجمع اتجاه الذراعين بين الملاحة المتنقلة والمعالجة. توجد هياكل أولية لوصف الأذرع والتحكم والواجهات وMoveIt، لكن التكامل والتخطيط والتحقق من الثبات والآلية النهائية غير مكتملة.", points: ["فصل مسؤوليات القاعدة والأذرع وأدوات النهاية", "تنسيق الحمولة والمدى والثبات والطاقة والسلامة", "التحقق من الانتقال بين الملاحة والمعالجة في سيناريوهات قابلة للتكرار"] },
      { ...english.showcase.views[2], label: "الوصول إلى الرفوف", short: "وصول رأسي", status: "مرجع تطبيقي / دراسة أولية", title: "توسيع الاستقلالية المتنقلة إلى التخزين الرأسي.", body: "يمثل الوصول إلى الرفوف دراسة مستقبلية لوحدة وآلية تخدم الجرد والفحص والاسترجاع في الارتفاعات. توضح الصورة فئة التطبيق ولا تمثل هندسة AMR-X معتمدة.", points: ["معاملة الرفع أو التسلق كوحدة ذات حدود صريحة", "الحفاظ على التموضع وثبات الحمولة وتجنب العوائق والاستعادة", "تحديد حالة مرئية ومسار تراجع آمن لكل حركة رأسية"] }
    ] },
    product: { ...english.product, eyebrow: "رؤية المنتج", title: "منصة تتغير مع المهمة.", body: "تبقى الحركة والطاقة والسلامة والاستقلالية في القاعدة، بينما تتغير المعدات الخاصة بالمهمة في الأعلى.", cta: "اكتشف AMR-X" },
    solutions: { ...english.solutions, title: "أتمتة قابلة للتكيف مع الاحتياجات التشغيلية.", body: "تستهدف الرؤية الأعمال الداخلية المتكررة حيث تتطور الحركة وأدوات المهمة بصورة مستقلة." },
    vision: { ...english.vision, eyebrow: "اتجاه المشروع", title: "جعل الروبوتات المتقدمة أسهل في التكيّف والتحقق والتشغيل." },
    partners: { ...english.partners, eyebrow: "منظومة تعاونية", title: "الروبوتات الأفضل تُبنى عبر تخصصات متعددة.", cta: "استكشف الشراكات", ecosystem: "المنظومة التقنية" },
    blog: { ...english.blog, title: "أفكار وتقدم ورؤية للمنتج.", read: "اقرأ المقال" },
    contact: { ...english.contact, title: "لنستكشف أين يمكن لـ AMR-X تقديم قيمة.", fields: { name: "الاسم", email: "البريد المهني", organization: "المؤسسة", subject: "مجال الاهتمام", message: "صف الفرصة", send: "إرسال الاستفسار" } },
    common: { learn: "اعرف المزيد", contact: "اتصل بنا", viewSolutions: "شاهد الحلول" },
    footer: { ...english.footer, summary: "رؤية لروبوت متنقل ذاتي ومعياري لعمليات داخلية قابلة للتكيف.", explore: "استكشف", connect: "تواصل", legal: "قانوني", social: "تابعنا", product: "المنتجات", solutions: "الحلول", partners: "الشركاء", blog: "المدونات", contact: "اتصل بنا", impressum: "بيانات الناشر", privacy: "الخصوصية", terms: "شروط الاستخدام", instagramSoon: "إنستغرام — قريبًا", copyright: "جميع الحقوق محفوظة.", rights: "رؤية منتج AMR-X. التصورات المعروضة قابلة للتطوير المستمر." },
  },
};

for (const locale of Object.keys(localized)) {
  localized[locale] = {
    ...english,
    ...localized[locale],
    pageHeroes: english.pageHeroes,
  };
}

export const showroomContent = { en: english, ...localized };
