<?xml version="1.0"?>
<package format="3">
  <name>arm_control</name>
  <version>0.1.0</version>
  <description>ros2_control configuration for the arm module joints.</description>
  <maintainer email="zeyneb@amr-x.local">ZEYNEB</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>ros2_control</exec_depend>
  <exec_depend>ros2_controllers</exec_depend>
  <exec_depend>controller_manager</exec_depend>
  <exec_depend>ros_gz_sim</exec_depend>
  <exec_depend>arm_description</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
