#!/usr/bin/env python3
"""Generate LaTeX project specification files from config/project_specs.json."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SPECS_PATH = ROOT / "config" / "project_specs.json"
OUTPUT_DIR = ROOT / "reports" / "v1_product_definition" / "tables" / "generated"


def latex_escape(value: object) -> str:
    text = str(value)
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(char, char) for char in text)


def latex_escape_breakable(value: object) -> str:
    return (
        latex_escape(value)
        .replace(r"\_", r"\_\allowbreak{}")
        .replace("/", r"/\allowbreak{}")
        .replace("-", r"-\allowbreak{}")
    )


def macro_name(section: str, key: str) -> str:
    parts = f"{section}_{key}".split("_")
    return "Spec" + "".join(part.capitalize() for part in parts)


def flatten_specs(specs: dict[str, object]) -> list[tuple[str, str, object]]:
    rows: list[tuple[str, str, object]] = []
    for section, values in specs.items():
        if isinstance(values, dict):
            for key, value in values.items():
                rows.append((section, key, value))
    return rows


def main() -> None:
    specs = json.loads(SPECS_PATH.read_text(encoding="utf-8"))
    rows = flatten_specs(specs)
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    macros = [
        r"% !TEX root = ../../main.tex",
        "% Generated by tools/generate_specs.py. Do not edit manually.",
        "",
    ]
    for section, key, value in rows:
        macros.append(
            rf"\newcommand{{\{macro_name(section, key)}}}{{{latex_escape(value)}}}"
        )
    macros.append("")
    (OUTPUT_DIR / "project_specs.tex").write_text("\n".join(macros), encoding="utf-8")

    table = [
        r"% !TEX root = ../../main.tex",
        "% Generated by tools/generate_specs.py. Do not edit manually.",
        r"\small",
        r"\begin{longtable}{>{\raggedright\arraybackslash}p{0.24\textwidth}>{\raggedright\arraybackslash}p{0.36\textwidth}>{\raggedright\arraybackslash}p{0.28\textwidth}}",
        r"\toprule",
        r"Section & Field & Value \\",
        r"\midrule",
        r"\endhead",
    ]
    for section, key, value in rows:
        table.append(
            f"{latex_escape_breakable(section)} & {latex_escape_breakable(key)} & {latex_escape_breakable(value)} \\\\"
        )
    table.extend([r"\bottomrule", r"\end{longtable}", r"\normalsize", ""])
    (OUTPUT_DIR / "project_specs_table.tex").write_text(
        "\n".join(table), encoding="utf-8"
    )


if __name__ == "__main__":
    main()
