cmake_minimum_required(VERSION 3.8)
project(navigation)

find_package(ament_cmake REQUIRED)

install(
  DIRECTORY config launch maps rviz behavior_trees
  DESTINATION share/${PROJECT_NAME}
)

install(PROGRAMS
  scripts/scan_filter_node.py
  scripts/scan_merger_node.py
  scripts/mission_server_node.py
  scripts/dashboard_navigation_node.py
  DESTINATION lib/${PROJECT_NAME}
)

install(FILES scripts/dashboard_navigation_math.py
  DESTINATION lib/${PROJECT_NAME}
)

if(BUILD_TESTING)
  find_package(ament_lint_auto REQUIRED)
  ament_lint_auto_find_test_dependencies()
endif()

ament_package()
